version: "2.1"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /docker/mosquitto/log:/mosquitto/log
      - /docker/mosquitto/data:/mosquitto/data
    ports:
      - 1883:1883
      - 9001:9001
    restart: always
