version: "2.1"
services:
  code-server:
    image: linuxserver/code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /docker/code-server/config:/config
    ports:
      - 8843:8443
    restart: unless-stopped
