version: "3.4"

services:
  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1901:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Paris
      #- PLEX_CLAIM=claim-xxxxxxxxxxxxxxxx  #obtain claim token https://plex.tv/claim expire within 4 minutes.
      - ADVERTISE_IP=http://192.168.1.10:32400/
      - PLEX_UID=1000
      - PLEX_GID=1000
    hostname: Plex-Server
    volumes:
      - /docker/plex/conf:/config
      - /docker/plex/data/transcode:/transcode
      - /docker/plex/data/tv:/media/tv
      - /docker/plex/data/movies:/media/movies
    devices:
      - /dev/dri:/dev/dri
    mem_limit: 4096m

  tautulli:
    image: tautulli/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /docker/tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    ports:
      - 8181:8181
    depends_on:
      - plex

