version: '2'

services:
  guacd:
    image: guacamole/guacd:latest
    container_name: guacd
    volumes:
      - /docker/guacamole/drive:/drive
      - /docker/guacamole/record:/record
    restart: unless-stopped
    
  guacamole-db:
    image: postgres:13
    container_name: guacamole-db
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: guacamole
      POSTGRES_USER: guacamole
      TZ: Europe/Paris
    volumes:
      - /docker/guacamole/init:/docker-entrypoint-initdb.d:ro  # To be remove/commented after first start
      - /docker/guacamole/data:/var/lib/postgresql/data
    restart: unless-stopped

  guacamole:
    image: guacamole/guacamole:latest
    container_name: guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_PASSWORD: guacamole
      POSTGRES_USER: guacamole
      TZ: Europe/Paris
      #TOTP_ENABLED: 'true'
    depends_on:
      - guacd
      - guacamole-db
    ports:
      - 8084:8080
    restart: unless-stopped
