version: "3.4"

services:
  paperless-broker:
    image: redis:6.0
    container_name: paperless-broker
    restart: unless-stopped
    volumes:
      - /docker/paperless/broker:/data

  paperless-db:
    image: postgres:13
    container_name: paperless-db
    restart: unless-stopped
    volumes:
      - /docker/paperless/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    depends_on:
      - paperless-db
      - paperless-broker
    ports:
      - 8010:8000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - /docker/paperless/data:/usr/src/paperless/data
      - /docker/paperless/export:/usr/src/paperless/export
      - /docker/paperless/documents:/usr/src/paperless/media
      - /docker/paperless/consume:/usr/src/paperless/consume
    environment:
      USERMAP_UID: 1000
      USERMAP_GID: 1000
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_TIME_ZONE: Europe/Paris
      PAPERLESS_OCR_LANGUAGE: fra
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{title}"
