version: '3.2'
networks:
  default: 
    name: NAME
    external: true
services:
  app:
    image: nanawel/our-shopping-list:latest
    restart: always
    ports:
      - '8083:8080'
    environment:
      # Default values below
      VUE_APP_I18N_LOCALE: en
      VUE_APP_I18N_FALLBACK_LOCALE: en
      VUE_APP_I18N_FORCE_LOCALE: 0
      VUE_APP_SINGLEBOARD_MODE: 0
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    volumes:
      - /docker/shoppinglist/dbdata:/data/db
