version: '2'
services:
  homebridge:
    image: oznu/homebridge:latest
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1000
      - PUID=1000
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - PACKAGES=ffmpeg.ffmpeg-libs
      - TZ=Europe/Paris
    volumes:
      - /docker/homebridge:/homebridge
