---
version: "2.1"
services:
  pyload-ng:
    image: linuxserver/pyload-ng
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /docker/pyload/config:/config
      - /docker/pyload/downloads:/downloads
    ports:
      - 8000:8000
      #- 9666:9666 #optional
    restart: unless-stopped

